# 📊 Reto 3 – Funciones y estadísticas en Pandas

**Objetivo:** aplicar funciones estadísticas y crear nuevas columnas basadas en cálculos.

In [ ]:
import pandas as pd
datos = pd.read_csv('../data/4_resultados_agua.csv')

### 🔹 Ejemplo de función personalizada
Crea una función que clasifique el pH:

In [ ]:
def clasificar_ph(valor):
    if valor < 6.5:
        return 'Ácido'
    elif valor <= 8.5:
        return 'Neutro'
    else:
        return 'Básico'

datos['categoria_ph'] = datos['pH'].apply(clasificar_ph)
datos.head()

### 💡 Actividad
- Calcula promedios de variables numéricas.
- Aplica al menos una función con `apply()` o `groupby()`.

In [ ]:
# Tu código aquí

# Reto 3: Funciones estadísticas y nuevas columnas

**Nombre:** Lizeth León  
**Tema asociado:** Residuos sólidos  
**Dataset:** data/4_resultados_agua.csv  

En este notebook se calculan estadísticas básicas de variables ambientales relacionadas con calidad del agua. Además, se crean nuevas columnas que permiten interpretar mejor los resultados del monitoreo.

In [8]:
import pandas as pd

df = pd.read_csv("../data/4_resultados_agua.csv")

df.head()

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
2     C  19.80  6.85          4.9
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

In [9]:
df["Temp_corregida"] = df["Temp"] + 0.5
df["OD_indice"] = df["OD_promedio"] * 10

df.head()

  Punto   Temp    pH  OD_promedio  Temp_corregida  OD_indice
0     A  22.25  7.15          6.2           22.75       62.0
1     B  24.30  7.20          5.8           24.80       58.0
2     C  19.80  6.85          4.9           20.30       49.0
3     D  23.65  7.05          6.5           24.15       65.0
4     E  25.15  7.25          5.0           25.65       50.0

In [10]:
resumen = df.groupby("Punto")[["Temp", "pH", "OD_promedio"]].mean()
resumen

        Temp    pH  OD_promedio
Punto
A      22.25  7.15          6.2
B      24.30  7.20          5.8
C      19.80  6.85          4.9
D      23.65  7.05          6.5
E      25.15  7.25          5.0

## Conclusión

El uso de funciones estadísticas en Pandas permite analizar de manera eficiente la calidad del agua. 
Desde el enfoque de residuos sólidos, estos resultados pueden ayudar a identificar posibles impactos de la contaminación en variables como pH, temperatura y oxígeno disuelto.