# 🧩 Reto 4 – Integración final de resultados

**Objetivo:** combinar los resultados de los retos anteriores para obtener un diagnóstico integral de la calidad del agua.

### 🔹 Instrucciones
- Importa los resultados obtenidos en los notebooks anteriores.
- Integra los análisis (pH, temperatura, oxígeno) en un solo DataFrame.
- Realiza una conclusión general del estado del agua.

In [ ]:
# Tu código aquí

#import pandas as pd
#datos = pd.read_csv('../data/4_resultados_agua.csv')

# Reto 4: Integración final y diagnóstico ambiental

**Nombre:** Lizeth León  
**Tema asociado:** Cobertura vegetal  
**Dataset:** data/4_resultados_agua.csv  

Este notebook integra los resultados del análisis de calidad del agua para generar un diagnóstico ambiental general. Se relaciona la interpretación con la importancia de la cobertura vegetal en la protección de fuentes hídricas.

In [3]:
import pandas as pd

df = pd.read_csv("../data/4_resultados_agua.csv")

df.head()

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
2     C  19.80  6.85          4.9
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

In [4]:
resumen_sitio = df.groupby("Punto")[["Temp", "pH", "OD_promedio"]].mean()
resumen_sitio

        Temp    pH  OD_promedio
Punto
A      22.25  7.15          6.2
B      24.30  7.20          5.8
C      19.80  6.85          4.9
D      23.65  7.05          6.5
E      25.15  7.25          5.0

In [5]:
diagnostico = resumen_sitio.copy()
diagnostico["interpretacion"] = "La cobertura vegetal protege la calidad del agua"
diagnostico

,Temp,pH,OD_promedio,interpretacion
Punto,,,,
A,22.25,7.15,6.2,La cobertura vegetal protege la calidad del agua
B,24.30,7.20,5.8,La cobertura vegetal protege la calidad del agua
C,19.80,6.85,4.9,La cobertura vegetal protege la calidad del agua
D,23.65,7.05,6.5,La cobertura vegetal protege la calidad del agua
E,25.15,7.25,5.0,La cobertura vegetal protege la calidad del agua