# ⚙️ Reto 2 – Filtros y condiciones en Pandas

**Objetivo:** aplicar filtros y condiciones lógicas para clasificar los datos.

In [ ]:
import pandas as pd
datos = pd.read_csv('../data/4_resultados_agua.csv')

### 🔹 Ejemplo de comparación
Puedes filtrar las filas según una condición, por ejemplo pH mayor a 8.5:

In [ ]:
datos[datos['pH'] > 8.5]

### 💡 Actividad
- Crea al menos dos condiciones (por pH y temperatura).
- Genera una nueva columna con la categoría resultante.

In [1]:
import pandas as pd

datos = pd.read_csv("../data/4_resultados_agua.csv")

datos.head()

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
2     C  19.80  6.85          4.9
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

In [2]:
ph_alto = datos[datos["pH"] > 7.5]
ph_alto

Empty DataFrame
Columns: [Punto, Temp, pH, OD_promedio]
Index: []

In [3]:
temp_alta = datos[datos["Temp"] > 24]
temp_alta

  Punto   Temp    pH  OD_promedio
1     B  24.30  7.20          5.8
4     E  25.15  7.25          5.0

In [4]:
def clasificar_calidad(row):
    if row["pH"] >= 6.5 and row["pH"] <= 8.5 and row["OD_promedio"] >= 5:
        return "Buena"
    else:
        return "Regular o mala"

datos["Calidad_agua"] = datos.apply(clasificar_calidad, axis=1)

datos

  Punto   Temp    pH  OD_promedio    Calidad_agua
0     A  22.25  7.15          6.2           Buena
1     B  24.30  7.20          5.8           Buena
2     C  19.80  6.85          4.9  Regular o mala
3     D  23.65  7.05          6.5           Buena
4     E  25.15  7.25          5.0           Buena

## Interpretación

Se aplicaron condiciones sobre el pH y la temperatura para identificar cambios en la calidad del agua.

Además, se creó una nueva columna llamada "Calidad_agua", que clasifica los datos en función del pH y el oxígeno disuelto.