# 📘 Reto 1 – Lectura y exploración de datos con Pandas

**Objetivo:** cargar el archivo CSV y realizar una exploración básica de los datos.

In [1]:
import pandas as pd

# 1. Cargar el archivo CSV
datos = pd.read_csv('../data/4_resultados_agua.csv')

# 2. Visualizar las primeras filas
datos.head()

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
2     C  19.80  6.85          4.9
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

In [2]:
datos.columns

Index(['Punto', 'Temp', 'pH', 'OD_promedio'], dtype='str')

In [3]:
datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Punto        5 non-null      str
 1   Temp         5 non-null      float64
 2   pH           5 non-null      float64
 3   OD_promedio  5 non-null      float64
dtypes: float64(3), str(1)
memory usage: 292.0 bytes

In [4]:
datos.describe()

            Temp        pH  OD_promedio
count   5.000000  5.000000     5.000000
mean   23.030000  7.100000     5.680000
std     2.093621  0.158114     0.712039
min    19.800000  6.850000     4.900000
25%    22.250000  7.050000     5.000000
50%    23.650000  7.150000     5.800000
75%    24.300000  7.200000     6.200000
max    25.150000  7.250000     6.500000

### 🔍 Análisis
- Identifica las columnas disponibles.
- Describe los tipos de datos y posibles valores nulos.

## Resultados del análisis

Las columnas del dataset son:
- Sitio
- Temperatura
- pH
- Oxigeno

Los datos son de tipo numérico (float) excepto el sitio.

No se observan valores nulos.

Los valores de pH están cercanos a 7, indicando condiciones neutras.

In [5]:
import pandas as pd

# Cargar datos
df = pd.read_csv("../data/4_resultados_agua.csv")

# Ver primeras filas
df.head()

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
2     C  19.80  6.85          4.9
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Punto        5 non-null      str
 1   Temp         5 non-null      float64
 2   pH           5 non-null      float64
 3   OD_promedio  5 non-null      float64
dtypes: float64(3), str(1)
memory usage: 292.0 bytes

In [7]:
df.describe()

            Temp        pH  OD_promedio
count   5.000000  5.000000     5.000000
mean   23.030000  7.100000     5.680000
std     2.093621  0.158114     0.712039
min    19.800000  6.850000     4.900000
25%    22.250000  7.050000     5.000000
50%    23.650000  7.150000     5.800000
75%    24.300000  7.200000     6.200000
max    25.150000  7.250000     6.500000

In [8]:
df.columns

Index(['Punto', 'Temp', 'pH', 'OD_promedio'], dtype='str')