# 📘 Reto 1 – Lectura y exploración de datos con Pandas

**Objetivo:** cargar el archivo CSV y realizar una exploración básica de los datos.

# Reto 1: Lectura y exploración de datos

En este notebook se carga el archivo `4_resultados_agua.csv` y se realiza una exploración inicial.

In [9]:
import pandas as pd

df = pd.read_csv("../data/4_resultados_agua.csv")

df.head()

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
2     C  19.80  6.85          4.9
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

## Revisión de columnas

In [10]:
df.columns

Index(['Punto', 'Temp', 'pH', 'OD_promedio'], dtype='str')

## Información del dataset

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Punto        5 non-null      str
 1   Temp         5 non-null      float64
 2   pH           5 non-null      float64
 3   OD_promedio  5 non-null      float64
dtypes: float64(3), str(1)
memory usage: 292.0 bytes

## Estadísticas

In [12]:
df.describe()

            Temp        pH  OD_promedio
count   5.000000  5.000000     5.000000
mean   23.030000  7.100000     5.680000
std     2.093621  0.158114     0.712039
min    19.800000  6.850000     4.900000
25%    22.250000  7.050000     5.000000
50%    23.650000  7.150000     5.800000
75%    24.300000  7.200000     6.200000
max    25.150000  7.250000     6.500000

## Valores faltantes

In [13]:
df.isnull().sum()

Punto          0
Temp           0
pH             0
OD_promedio    0
dtype: int64

## Conclusión

Se realizó la carga y exploración del dataset de calidad del agua.

In [14]:
import pandas as pd

df = pd.read_csv("../data/4_resultados_agua.csv")

df.head()

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
2     C  19.80  6.85          4.9
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Punto        5 non-null      str
 1   Temp         5 non-null      float64
 2   pH           5 non-null      float64
 3   OD_promedio  5 non-null      float64
dtypes: float64(3), str(1)
memory usage: 292.0 bytes

In [16]:
df.describe()

            Temp        pH  OD_promedio
count   5.000000  5.000000     5.000000
mean   23.030000  7.100000     5.680000
std     2.093621  0.158114     0.712039
min    19.800000  6.850000     4.900000
25%    22.250000  7.050000     5.000000
50%    23.650000  7.150000     5.800000
75%    24.300000  7.200000     6.200000
max    25.150000  7.250000     6.500000

In [17]:
df.isnull().sum()

Punto          0
Temp           0
pH             0
OD_promedio    0
dtype: int64

In [19]:
df.columns

Index(['Punto', 'Temp', 'pH', 'OD_promedio'], dtype='str')

## Conclusión

El dataset contiene información de calidad del agua en diferentes puntos de muestreo. 
Se identificaron variables como temperatura, pH y oxígeno disuelto, las cuales permiten evaluar el estado del recurso hídrico.